### ISSUE TITLE
Add code standard doc to web UI

### ISSUE THREAD

**Issue by eethann** [ProjectDrawdown/global-research-platform-web-ui#13] opened 2021-06-08 14:01 UTC
Document some code formatting, programming paradigm, and code organization standards. E.g. linting spec, what sorts of reducers to make, and where major files should go.

**Comment by colleenskemp** [comment] 2021-06-13 22:48
This is a duplicate of issue https://github.com/ProjectDrawdown/global-research-platform-web-ui/issues/16
content copied over and closing this issue.

**Closed** 2021-06-13 22:49 UTC
